// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYNaOLfcQE8kUYuSRA_YF3QZLyLVd_qV4',
    appId: '1:122691896387:web:08c9afe7a5e416a7eec0f6',
    messagingSenderId: '122691896387',
    projectId: 'recipe-app-4d02d',
    authDomain: 'recipe-app-4d02d.firebaseapp.com',
    storageBucket: 'recipe-app-4d02d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiuDtepnm-HFjeCVDohDXEs5qJo1fnFHA',
    appId: '1:122691896387:android:63fc985b08748a27eec0f6',
    messagingSenderId: '122691896387',
    projectId: 'recipe-app-4d02d',
    storageBucket: 'recipe-app-4d02d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-CTTTQ0Bdk8tEEGtJLgnsTO7H0lPe3Sg',
    appId: '1:122691896387:ios:a966e904d3a06a08eec0f6',
    messagingSenderId: '122691896387',
    projectId: 'recipe-app-4d02d',
    storageBucket: 'recipe-app-4d02d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-CTTTQ0Bdk8tEEGtJLgnsTO7H0lPe3Sg',
    appId: '1:122691896387:ios:a966e904d3a06a08eec0f6',
    messagingSenderId: '122691896387',
    projectId: 'recipe-app-4d02d',
    storageBucket: 'recipe-app-4d02d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYNaOLfcQE8kUYuSRA_YF3QZLyLVd_qV4',
    appId: '1:122691896387:web:32c8966373676c5deec0f6',
    messagingSenderId: '122691896387',
    projectId: 'recipe-app-4d02d',
    authDomain: 'recipe-app-4d02d.firebaseapp.com',
    storageBucket: 'recipe-app-4d02d.firebasestorage.app',
  );
}
